### ISSUE TITLE
Have vertical slider option.

### ISSUE THREAD

**Issue by jxxcarlson** [carwow/elm-slider#21]

**Comment by vincentnavetat** [comment]
We don't have plans to add this feature at the moment. Looking at the Mozilla doc, it seems the best way to implement it would be via a rotation in CSS. 

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range

**Comment by jxxcarlson** [comment]
Thanks so much.  That is what I have done for the time being.



Jim
https://jxxcarlson.io
