### ISSUE TITLE
sliders not matching with blue selection

### ISSUE THREAD

**Issue by staeter** [carwow/elm-slider#31]
I used the /example/example.css and I made sure I was doing exactly the same as in /example/Main.elm

![Annotation2020-02-10](https://user-images.githubusercontent.com/35398967/75138404-6b415080-56ea-11ea-8a9c-b946b9adf096.png)
The problem as you can see on the picture is that the double slider's cursors don't go all the way along the slider.

Also the simple slider's blue area doesn't folow the cursor.

**Comment by vincentnavetat** [comment]
Hello,

This has been fixed in v11.1.3

Apologies for the issue and the slow response!
